version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  machine-learning-client:
    build:
      context: ./machine-learning-client
    container_name: ml_client
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
  web-app:
    build:
      context: ./web-app
    container_name: web_app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
volumes:
  mongodb_data:
