name: Web Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r web-app/requirements.txt

    # Run tests with pytest and coverage
    - name: Run Unit Tests
      run: |
        pip install pytest pytest-flask pytest-cov
        pytest web-app/tests --cov=web-app --cov-fail-under=80

    # Lint the code using pylint
    - name: Lint Code with Pylint
      run: |
        pip install pylint
        pylint web-app/*.py

    # Format the code using Black
    - name: Format Code with Black
      run: |
        pip install black
        black web-app
